[package]
name = "GameTools"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
simplelog = "0.12.2"
x11 = "2.21.0"
grab = "0.3.1"
evdev = "0.13.0"
rdev = "0.5.3"
json = "0.12.4"
crossbeam = "0.8.4"